development:
  adapter: postgresql
  encoding: unicode
  database: mymemory_development
  pool: 5
  username: fivesci
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: mymemory_test
  pool: 5
  username: fivesci
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: mymemory_production
  pool: 5
  username: fivesci
  password:

cucumber:
  <<: *test
