development:
  adapter: postgresql
  encoding: unicode
  database: mymemo
  pool: 5
  username: mymemo
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: mymemo
  pool: 5
  username: mymemo
  password: